
import { Translations, Language } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    welcome: "Welcome to CeloraAI",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Your Name",
    continueWithGoogle: "Continue with Google",
    continueWithApple: "Continue with Apple",
    home: "Home",
    chats: "Chats",
    settings: "Settings",
    profile: "Profile",
    products: "Our Products",
    help: "Help Center",
    language: "Language",
    theme: "Theme",
    lightMode: "Light",
    darkMode: "Dark",
    logout: "Logout",
    newChat: "New Chat",
    typeMessage: "Type your message...",
    howToUse: "How to Use",
    whyNeed: "Why is it needed?",
    howHelp: "How will it help?",
    faq: "FAQ",
    whatIsCelora: "What is CeloraAI?",
    isDataSafe: "Is my data safe?",
    whoIsElement: "Who are Element Intelligent?",
    comingSoon: "Soon in development",
    deleteChat: "Delete",
    resumeChat: "Resume",
    showNav: "Show Navigation",
    hideNav: "Hide Navigation",
  },
  ru: {
    welcome: "Добро пожаловать в CeloraAI",
    login: "Вход",
    register: "Регистрация",
    email: "Электронная почта",
    password: "Пароль",
    name: "Ваше имя",
    continueWithGoogle: "Продолжить через Google",
    continueWithApple: "Продолжить через Apple",
    home: "Главная",
    chats: "Чаты",
    settings: "Настройки",
    profile: "Профиль",
    products: "Наши продукты",
    help: "Центр помощи",
    language: "Язык",
    theme: "Тема",
    lightMode: "Светлая",
    darkMode: "Темная",
    logout: "Выйти",
    newChat: "Новый чат",
    typeMessage: "Введите сообщение...",
    howToUse: "Как пользоваться",
    whyNeed: "Зачем он нужен?",
    howHelp: "Как поможет?",
    faq: "Часто задаваемые вопросы",
    whatIsCelora: "Что такое CeloraAI?",
    isDataSafe: "Безопасно ли хранить данные?",
    whoIsElement: "Кто такие Element Intelligent?",
    comingSoon: "Скоро в разработке",
    deleteChat: "Удалить",
    resumeChat: "Продолжить",
    showNav: "Показать меню",
    hideNav: "Скрыть меню",
  },
  uz: {
    welcome: "CeloraAI-ga xush kelibsiz",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    email: "Email",
    password: "Parol",
    name: "Ismingiz",
    continueWithGoogle: "Google orqali davom etish",
    continueWithApple: "Apple orqali davom etish",
    home: "Bosh sahifa",
    chats: "Chatlar",
    settings: "Sozlamalar",
    profile: "Profil",
    products: "Mahsulotlarimiz",
    help: "Yordam markazi",
    language: "Til",
    theme: "Mavzu",
    lightMode: "Yorug'",
    darkMode: "To'q",
    logout: "Chiqish",
    newChat: "Yangi chat",
    typeMessage: "Xabarni yozing...",
    howToUse: "Qanday foydalanish kerak",
    whyNeed: "Nima uchun kerak?",
    howHelp: "Qanday yordam beradi?",
    faq: "Ko'p so'raladigan savollar",
    whatIsCelora: "CeloraAI nima?",
    isDataSafe: "Ma'lumotlar xavfsizmi?",
    whoIsElement: "Element Intelligent kimlar?",
    comingSoon: "Tez orada ishlab chiqiladi",
    deleteChat: "O'chirish",
    resumeChat: "Davom etish",
    showNav: "Menyuni ko'rsatish",
    hideNav: "Menyuni yashirish",
  }
};
